[package]
name = "hello"
version = "0.1.0"
authors = ["tomoyuki-nakabayashi <tomo.wait.for.it.yuki@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
volatile = "0.2.3"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"